from abc import ABC, abstractmethod
import os.path
import json

# from commmon.app import App
# from common.api import Api
# from commmon.database import Database
# from commmon.helpers import Helpers


class Insertor(ABC):
    """
    Insertor abstract class (insert_from_xxx)
    """

    @abstractmethod
    def read(self, filename):
        pass

    @abstractmethod
    def preprocess(self):
        pass

    @abstractmethod
    def insert(self):
        pass


class InsertFromJsonl(Insertor):
    """
    Insert from .jsonl files. In this context, those files are generated by the twarc module.
    This class handles FLATTENED (1 tweet per line) jsonl files (see twarc documentation).
    """

    def __init__(self, app):
        self.app = app
        self.jsonl_path = os.path.join(self.app.root_dir, "database", "jsonl", "flat")

    def read(self, filename):
        """
        Open and extract each line with this generator.
        """

        with open(
            os.path.join(self.jsonl_path, filename),
            encoding="utf8",
        ) as open_f:
            for line in open_f:
                yield json.loads(line)

    def get_tot_lines(self, filename):
        """
        Return the total number of lines of a file.
        """

        with open(
            os.path.join(self.jsonl_path, filename),
            encoding="utf8",
        ) as open_f:
            tot_lines = 0
            for _ in open_f:
                tot_lines += 1
        return tot_lines

    def preprocess(self):
        pass

    def insert(self):
        pass


# TODO:
# add insert_from_file.py
# add insert_from_url.py
