name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas "tweepy==3.10" python-dotenv tqdm
    - name: Unit tests
      env:
        BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
        KEY: ${{ secrets.KEY }}
        KEY_SECRET: ${{ secrets.KEY_SECRET }}
        TOKEN: ${{ secrets.TOKEN }}
        TOKEN_SECRET: ${{ secrets.TOKEN_SECRET }}
      run: |
        cd tests
        python -m unittest discover
